### ISSUE TITLE
module_utils/cloud.py is licensed GPLv3+

### ISSUE THREAD

**Issue by abadger** [ansible-collections/amazon.aws#131]
##### SUMMARY
This module_utils file is licensed GPLv3+ rather than BSD:

https://github.com/ansible-collections/amazon.aws/blob/main/plugins/module_utils/cloud.py

This was a problem in the ansible/ansible repo as module_utils files were supposed to be licensed BSD so that third parties could use the code even if their code was licensed under an GPLv3 incompatible license.  I'm not sure if the same policy exists for the amazon.aws collection.  If not, you can close this (and you may want to license new contributions to the other module_utils files under the GPLv3+ so that it's easier to explain the licensing requirements).

If that policy does hold, then you'll need to do something about this file.  The PR in the ansible/ansible repo never got sign off from the author and other contributors: https://github.com/ansible/ansible/pull/28372 so you may need to reimplement this functionality from scratch rather than getting it relicensed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* https://github.com/ansible-collections/amazon.aws/blob/main/plugins/module_utils/cloud.py

##### ANSIBLE VERSION

Problem exists in current HEAD: 5cfd13042960f068b9b2ea9b0f13802bce285ad3

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by jillr** [comment]
@abadger Thanks for bringing this up. We're not currently deviating from the general Ansible project policies so this is definitely an issue.

**Comment by jillr** [comment]
To date we've gotten consent from every contributor except one (many via direct emails).  As we do not have agreement from all contributors we'll be re-implementing this.
