### ISSUE TITLE
Add ability to PUT files recursively to amazon.aws.s3_object module

### ISSUE THREAD

**Issue by bar0n36** [ansible-collections/amazon.aws#1431]
### Summary

In order to add functionality and make it somewhat equivalent to using the aws-cli, it would be good to be able to upload entire directories (so add a --recursive flag type feature) rather than just a single file.

I know this could potentially be resolved by looping through the list of files, but if the list is 10s of thousands of files long spread across hundreds of sub-directories, it would be much simpler to simply say 'recurisve: true' (and other 'copy' type modules do support recursive copy)

### Issue Type

Feature Idea

### Component Name

s3_object

### Additional Information

The feature would be used to upload whole directory structures to S3, when a single file is not particulartly feasible (eg: Large export of small files stored in a folder / sub-directories).

Would look something like the below in action:
```- name: Upload Directory to S3
  amazon.aws.s3_object:
    bucket: my_example_bucket
    object: "/my_directory_uploaded/"
    src: "/my_local_directory/sub-directory-to-upload"
    mode: put
    access_key: "ABC123"
    secret_key: "DEF456"
    recursive: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
@bar0n36 

Thanks for taking the time to open this feature request.

There is a separate module [`community.aws.s3_sync`](https://docs.ansible.com/ansible/latest/collections/community/aws/s3_sync_module.html) which already provides this feature.  At this time we don't plan on adding the functionality to s3_object.
