### ISSUE TITLE
elb_target_group doesn't change health_check_path on existing target group

### ISSUE THREAD

**Issue by briantist** [ansible-collections/amazon.aws#15]
##### SUMMARY
<s>The `health_check_path` option is ignored on an existing target group. Changing it gives a status of `ok` and the setting is not changed.

I suspect this affects more health check options but haven't tried them.
</s>

Turns out this is a duplicate of https://github.com/ansible/ansible/issues/50024

You have to supply `health_check_protocol` in order for `health_check_path` to be considered.

But the documentation still doesn't reflect that. 

And really, the purpose of the check is to ignore params that only apply to `http` and `https` protocols. The check should:
1. Throw an error (at least a warning?) when a the options that don't apply to your protocol are supplied
1. Assume the `health_check_protocol` is the same as `protocol` if the former is not supplied, since that's what happens in reality

So I think this should remain open.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

elb_target_group

##### ANSIBLE VERSION

2.9

##### STEPS TO REPRODUCE

* Create target group
* Change the `health_check_path` option to something else
* Run again

##### EXPECTED RESULTS

* `changed` status with updated value

##### ACTUAL RESULTS

* `ok` status with no change

**Comment by wimnat** [comment]
This and the other issues should reside in https://github.com/ansible-collections/community.aws not here as they are community supported modules.

**Comment by briantist** [comment]
@wimnat thanks I thought I had moved the rest but it turns out I only did one of them.

I think #8 should stay here though, as the problem resides in the module util backing both modules, not in the modules themselves.

---

This issue closed in favor of https://github.com/ansible-collections/community.aws/issues/29
