### ISSUE TITLE
amazon.aws:6.0.0 - 'LookupModule' object has no attribute 'get_options'

### ISSUE THREAD

**Issue by sandeepnethi** [ansible-collections/amazon.aws#1543]
### Summary

Newly released version 6.0.0 is throwing below error when calling a lookup plugin to read aws ssm parameter. Older version of modules are working as expected.

```
{"msg": "An unhandled exception occurred while running the lookup plugin 'aws_ssm'. Error was a <class 'AttributeError'>, original message: 'LookupModule' object has no attribute 'get_options'"}
```

### Issue Type

Bug Report

### Component Name

amazon.aws

### Ansible Version

```console (paste below)
$ ansible --version

ansible [core 2.11.12]
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

Collection Version
---------- -------
amazon.aws 6.0.0
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
```

### OS / Environment

Amazon linux 2

### Steps to Reproduce

Read ssm parameter using below lookup example 
```yaml (paste below)
"{{ lookup('aws_ssm', '<parameter_name>', region=ansible_ec2_placement_region) }}"
```

### Expected Results

Expected to get the value of the given ssm parameter name but it didn't work 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
Hi @sandeepnethi,

Thanks for taking the time to open this PR.  With release 6.0.0 we've dropped support for Ansible 2.11.

Please see:
https://github.com/ansible-collections/amazon.aws/blob/stable-6/README.md#ansible-version-compatibility
 and:
https://github.com/ansible-collections/amazon.aws/blob/stable-6/meta/runtime.yml

I would also add that Ansible Core 2.11 went end of life in November, and no longer receives any support or security fixes.

**Comment by sandeepnethi** [comment]
Thanks for the clarification @tremble
