### ISSUE TITLE
ec2 inventory plugin does not work without region or regions field

### ISSUE THREAD

**Issue by Zokormazo** [ansible-collections/amazon.aws#1551]
### Summary

According to https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html ec2 inventory plugin should retrieve nodes from all the regions except the restricted ones (eg gov ones) if you don't specify regions. `region` key is not documented there.

but starting 6.0 this does not work anymore.

Similar to the old https://github.com/ansible/ansible/issues/45288 a

### Issue Type

Bug Report

### Component Name

ec2_inventory

### Ansible Version

```console (paste below)
$  ansible --version
ansible [core 2.15.0rc2.post0]
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list

Collection                  Version
--------------------------- -------
amazon.aws                  6.0.0 
```

### AWS SDK versions

```console (paste below)
$ # pip3 show boto boto3 botocore
WARNING: Package(s) not found: boto
Name: boto3
Version: 1.24.95
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: jmespath, botocore, s3transfer
Required-by: 
---
Name: botocore
Version: 1.27.95
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: None
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: jmespath, python-dateutil, urllib3
Required-by: s3transfer, boto3

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg

```

### OS / Environment

ubi8 based execution environment

### Steps to Reproduce

```
plugin: amazon.aws.aws_ec2
#regions:
#  - us-east-1
# region: us-east-1
```

### Expected Results

Inventories plugin works against all unrestricted regions

### Actual Results

Inventory plugin fails because of lack of `regions`
```console (paste below)
* Failed to parse /runner/inventory/aws_ec2.yml with auto plugin:
The amazon.aws.aws_ec2 plugin requires a region and none was found in
configuration, environment variables or module parameters
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
@Zokormazo,

Thanks, that confirms the issue is where I thought it was and gives us a work around if necessary.  Hopefully, #1552 will properly fix the issue.

**Comment by Zokormazo** [comment]
Thanks for the fast turnaround !
