### ISSUE TITLE
rds_instance state definition refers to snapshots

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible-collections/amazon.aws#1574]
### Summary

The [documentation for `rds_instance`](https://docs.ansible.com/ansible/latest/collections/amazon/aws/rds_instance_module.html#ansible-collections-amazon-aws-rds-instance-module) says that the `state` parameter means:

> Whether the snapshot should exist or not. 

That doesn't sound right. Was this just a typo when someone was copy-pasting the docs for each parameter?

The remainder of the explanation, the parameter name, and the parameter values do not sound related to snapshots.

if `state` = `absent` or `terminated`, then whether or not you create a snapshot is relevant, but isn't that what `skip_final_snapshot` is for?

### Issue Type

Documentation Report

### Component Name

rds_instance

### Ansible Version

n/a

### Collection Versions

n/a

### Configuration

n/a

### OS / Environment

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by alinabuzachis** [comment]
@mdavis-xyz Thank you for raising this issue. I guess there's a copy/paste mismatch. Would you be willing to open a pull request with a fix for the documentation?
