### ISSUE TITLE
Configure the Instance Metadata Service version 2 (IMDSv2) for ec2_tags

### ISSUE THREAD

**Issue by nhoffman5** [ansible-collections/amazon.aws#165]
##### SUMMARY

Configure the ec2_tag module to be able to use AWS' Instance Metadata Service version 2 (IMDSv2).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_tag

##### ADDITIONAL INFORMATION

AWS is recommending that users configure their instances to use the IMDSv2. The ec2_tags module does not appear to be configured to allow usage of the IMDSv2. This would allow users to upgrade their instances to use the IMDSv2 while still being able to use their ansible deployments.

Looks like there is an existing PR for ec2_metadata_facts on the same issue: https://github.com/ansible-collections/amazon.aws/pull/43

**Comment by flowerysong** [comment]
I'm not sure what you're requesting; `ec2_tag` doesn't use either version of the instance metadata service, it calls the EC2 API.

**Comment by nhoffman5** [comment]
Looks like there was an issue on our end with our deployment method. The method we were getting our resource ID was the piece that broke with the instance metadata service v2 which resulted in ec2_tag failing. Thanks for the assistance!
