### ISSUE TITLE
Allow to filter out/exclude hosts from the inventory

### ISSUE THREAD

**Issue by Porkepix** [ansible-collections/amazon.aws#182]
##### SUMMARY
This can be for both EC2 and RDS inventory plugin.
Currently inventory can be built and restricted through "positive" filtering, ie. "I want it matches this tag" or "I want it to be in this state" and so on.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- `amazon.aws.aws_ec2`
- `amazon.aws.aws_rds`

##### ADDITIONAL INFORMATION
This would be greatly useful to be able to filter out/exclude hosts based on the same kind of rules and at the same time.
For example we currently get to filter only on running hosts, but from those hosts, a bunch of them we have no SSH access on because they are create by gitlab-runner to run its job and are completely managed by the runner. In this kind of case we need to filter out those hosts or we end-up having issues for playbooks running on the 'all' group.

**Comment by goneri** [comment]
Hi @Porkepix,

I understand this is what as powerful as what you describe here, but you can already use wildcard or regex on the host names: https://docs.ansible.com/ansible/devel/user_guide/intro_patterns.html

**Comment by goneri** [comment]
We feel like it's a good idea to be able to ignore some hosts in the inventory configuration. However this can also be beneficial if we build a common approach with the other inventory plugins. A discussion should be open at the ansible/ansible project level.
