### ISSUE TITLE
AWS inventory tags filtering does not support OR logic

### ISSUE THREAD

**Issue by tchellomello** [ansible-collections/amazon.aws#186]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Instance filters for AWS do not support the OR condition. 

Until previous versions specifying the instance filters as `tag:operating_system=rhel*, tag:OS=RHEL*` worked as an "OR" condition like it will display instances with either of the tags but with the latest version passing the instance filter as above seems to be taken as "AND" condition instead of "OR"  such that it will only display the instances that have both the tags. 

##### ENVIRONMENT
* AWX version: 15.0.0
* AWX install method: linux
* Ansible version:  2.9.12
* Operating System: Linux

##### STEPS TO REPRODUCE

Create an AWS dynamic inventory passing 2 tags

##### EXPECTED RESULTS

Results should consider `OR` as the same result when using the AWS webUI to filter it

##### ACTUAL RESULTS

The logic applied is `AND` instead `OR`

##### ADDITIONAL INFORMATION

To work around the problem and make AWS filter to work with `OR` logic, we performed the steps below:

     [1] Create a custom inventory script using https://raw.githubusercontent.com/ansible/ansible/stable-2.9/contrib/inventory/ec2.py

     [2] Create ec2.ini on all Tower servers:
          # cd /etc/ansible/
          # wget https://raw.githubusercontent.com/ansible/ansible/stable-2.9/contrib/inventory/ec2.ini
          # chown awx:awx ec2.ini
          # chmod 400 ec2.ini

     [3] Modify "ec2.ini" according to your environment, also you can set "INSTANCE FILTER" like below:
         ~~~
         instance_filters = tag:test_key0=foo,tag:test_key1=bar
         ~~~

    [4] Create inventory Source using [1] and set "EC2_INI_PATH" in the "ENVIRONMENT VARIABLES" section:
         ~~~
         ---
         EC2_INI_PATH: "/etc/ansible/ec2.ini"
         ~~~

See also: https://github.com/ansible/tower/issues/4655

**Comment by ikhan2010** [comment]
@goneri giving this one a bump.

**Comment by goneri** [comment]
The difference of behaviour is unfortunate but if we change the inventory plugin the way you describe, this will be a breaking change for the current users.
The use of `AND` by default is also consistent with the EC2 filters:  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html.

**Comment by goneri** [comment]
The use of a jmespath filter query (https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter) as suggested by @chrismeyersfsu here https://github.com/ansible/tower/issues/4655#issuecomment-756989706 is a better approach IMO.

I close this issue as `wontfix` and open up a new feature request.
