### ISSUE TITLE
cloudwatch_metric_alarm support config DatapointsToAlarm

### ISSUE THREAD

**Issue by owanio1992** [ansible-collections/amazon.aws#2193]
### Summary

the cloudwatch support "DatapointsToAlarm" with EvaluationPeriods [boto3 doc](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch/client/put_metric_alarm.html#CloudWatch.Client.put_metric_alarm:~:text=than%2086%2C400%20seconds.-,DatapointsToAlarm,-(integer)%20%E2%80%93%20The)

hope this module can support   

![image](https://github.com/user-attachments/assets/539718d9-bded-47aa-b641-7a09d0263ac3)

### Issue Type

Feature Idea

### Component Name

cloudwatch_metric_alarm

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by owanio1992** [comment]
here is my fixed code 
[cloudwatch_metric_alarm.zip](https://github.com/user-attachments/files/16230554/cloudwatch_metric_alarm.zip)

**Comment by abikouo** [comment]
@owanio1992 are you willing to open a pull request to add this feature? Thanks

**Comment by owanio1992** [comment]
@abikouo I create a PR, many thanks
