### ISSUE TITLE
ec2_metadata_facts: Add support to query instance tags + values

### ISSUE THREAD

**Issue by drewoconnor** [ansible-collections/amazon.aws#2293]
### Summary

https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_metadata_facts_module.html#return-ansible_facts/ansible_ec2_instance_tags_keys

States that it returns the keys. But, there is no way to get the values. 

Can we add a way to get the tag Values? 

### Issue Type

Feature Idea

### Component Name

ec2_metadata_facts

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
It's currently not very "obvious" but they are returned...

Running the integration test we have for this module:

```
TASK [amazon.aws.ec2_metadata_facts] *******************************************
...
ok: [34.239.124.147] => {
    "ansible_facts": {
        "ansible_ec2_ami_id": "ami-07320b1482d6ac29f",
...
        "ansible_ec2_instance_tags_keys": [
            "Name",
            "camelCaseKey",
            "snake_case_key"
        ],
...
        "ansible_ec2_tags_instance_Name": "ansible-test-28009695-ec2-metadata-facts",
        "ansible_ec2_tags_instance_camelCaseKey": "aCamelCaseValue",
        "ansible_ec2_tags_instance_snake_case_key": "a_snake_case_value",
        "ansible_ec2_user_data": "None"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "metadata_token_ttl_seconds": 240
        }
    }
}
```

The tag values are accessible under `ansible_ec2_tags_instance_<tag_name>`, so this is more a case of missing documentation bug than a missing feature.
