### ISSUE TITLE
ec2 inventory hostnames creation by combining instance data

### ISSUE THREAD

**Issue by vivanov-dp** [ansible-collections/amazon.aws#231]
##### SUMMARY

Allow combining different bits of instance data to form the hostname, for example:
```
hostnames:
  - tag:ServerType+instance-id
  - dns-name+private-ip+image-id
  - dns-name+tag:Group
  etc ...
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

aws_ec2 inventory plugin

##### ADDITIONAL INFORMATION

I'm using tags that group my instances in certain ways, and I prefer seeing the hosts in ansible logs named by these tags, for example - `log_server`, `backups`, etc, but since there are multiple hosts in each group, they override each other in the inventory, so I need a token to distinguish them. Adding the instance ID to the tag name seems the most rational way to do it, however I can't find anything in the docs about the aws_ec2 plugin that would allow me to achieve this.

I did a quick patch to the plugin, which enables the syntax in the example above:
```patch
--- aws_ec2.py     2021-01-08 11:07:41.259602467 +0000
+++ aws_ec2.py  2021-01-08 11:18:14.415506707 +0000
@@ -503,14 +503,21 @@
         if not hostnames:
             hostnames = ['dns-name', 'private-dns-name']

-        hostname = None
+        hostname = ''
         for preference in hostnames:
-            if 'tag' in preference:
-                if not preference.startswith('tag:'):
-                    raise AnsibleError("To name a host by tags name_value, use 'tag:name=value'.")
-                hostname = self._get_tag_hostname(preference, instance)
-            else:
-                hostname = self._get_boto_attr_chain(preference, instance)
+            bits = preference.split('+')
+            result = None
+            for bit in bits:
+                if 'tag' in bit:
+                    if not bit.startswith('tag:'):
+                        raise AnsibleError("To name a host by tags name_value, use 'tag:name=value'.")
+                    result = self._get_tag_hostname(bit, instance)
+                else:
+                    result = self._get_boto_attr_chain(bit, instance)
+                if result:
+                    if hostname:
+                        hostname += '-'
+                    hostname += result
             if hostname:
                 break
         if hostname:
```

Using it, I can get an inventory looking like this:
```
  ...
  |  |--b12tf-dev-efs-backups-i-0782...
  |  |--b12tf-gold-efs-backups-i-0573...
  |--@tag_gamesrv_host:
  |  |--b12tf-alpha-gamesrv-host-i-08d3...
  |  |--b12tf-dev-gamesrv-host-i-0b81...
  |  |--b12tf-gold-gamesrv-host-i-004a...
  |  |--b12tf-gold-gamesrv-host-i-0174...
  |  |--b12tf-gold-gamesrv-host-i-0235...
  |  |--b12tf-gold-gamesrv-host-i-02e4...
  |  |--b12tf-gold-gamesrv-host-i-0324...
  |  |--b12tf-gold-gamesrv-host-i-0389...
  |  | ....
  |--@tag_gamesrv_template:
  |  |--b12tf-alpha-gamesrv-template-i-0b35...
  |  |--b12tf-dev-gamesrv-template-i-0e5a...
  ...
```

I can't find the time to learn the project's requirements and actually check if it is conforming to everything that it needs to, so I'm not filling a pull request, but if you find it useful, feel free to modify&include it as you see fit.

I would be very grateful if some form of this makes it to the next release, so I wouldn't have to maintain the patch on my side.

**Comment by gravesm** [comment]
@vivanov-dp Thank you for posting this. We think https://github.com/ansible-collections/amazon.aws/pull/25 may solve this problem but it is not released yet in the current version. If you want you can try this before then and let us know if it solves your problem. 

We try to minimize the amount of changes we make to inventory plugins.

waiting_on_info

**Comment by vivanov-dp** [comment]
@gravesm Thanks, #25 solves my problem - even though it only allows 2 options to be concatenated, it's enough. I can use it once it gets released.

However, I see somebody commenting in an older linked issue, that they need more than 2 - https://github.com/ansible/ansible/issues/55911#issuecomment-653209122

**Comment by goneri** [comment]
Hi @vivanov-dp,

Thank you for your feedback. I close the issue.
