### ISSUE TITLE
amazon.aws.ec2 page incorrectly references ec2_instance in Synopsis/Note

### ISSUE THREAD

**Issue by jrglynn2** [ansible-collections/amazon.aws#251]
##### SUMMARY

In the "Synopsis" section, the "Note:" references the module 'amazon.aws.ec2_instance' twice  -  this should actually be the 'community.aws.ec2_instance' module

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

amazon.aws.ec2 

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Comment by gravesm** [comment]
@jrglynn2 Thank you for reporting this issue!

**Comment by jillr** [comment]
This bug report is entirely accurate, however we will be promoting the ec2_instance to supported status and migrating it into amazon.aws in the next week or so.  This status change will be in the 2.0 collection release.  Once that happens, the ec2.py docs will effectively be accurate.  Thanks for catching and reporting this docs bug!

**Comment by jillr** [comment]
The ec2_instance module has been moved to amazon.aws, in the `main` branch, and will be included in the next collection release.
https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/ec2_instance.py
