### ISSUE TITLE
IAM AWS Ansible Module won't return the Secret Access Key

### ISSUE THREAD

**Issue by lpossamai** [ansible-collections/amazon.aws#47]
##### SUMMARY
When using the [iam](https://docs.ansible.com/ansible/latest/modules/iam_module.html#parameter-access_key_state) module to create IAM users, I would expect to retrieve the nearly created **Access Key** and **Secret Access Key**.

However, the return data is only **Access Key**. The **Secret Access Key** is not displayed anywhere.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Ansible [iam](https://docs.ansible.com/ansible/latest/modules/iam_module.html) module.

##### ADDITIONAL INFORMATION

When using the [iam](https://docs.ansible.com/ansible/latest/modules/iam_module.html#parameter-access_key_state) module to create IAM users, I would expect to retrieve the nearly created **Access Key** and **Secret Access Key**.

However, the return data is only **Access Key**. The **Secret Access Key** is not displayed anywhere.

There is no other way to retrieve the **Secret Access Key** but when the **Access Key** is created. Therefore, even if I wanted to grab it on the console, it won't let me.

Below you can find some examples.

playbook.yml:

```
---
- name: "Starting the tasks: Creates IAM Policy, group, Role and User"
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws-credentials.yml

  tasks:

  - include: tasks/create-user.yml
    tags: user

  - include: tasks/create-group.yml
    tags: group
```

tasks/create-user.yml:

```
---
  # Create the IAM users with Console and API access
- name: Create new IAM users with API keys and console access
  iam:
    iam_type: user
    name: "{{ item }}"
    state: present
    password: "{{ lookup('password', 'passwordfile chars=ascii_letters') }}"
    access_key_state: create
    update_password: on_create
  no_log: true
  register: newusers
  loop:
    - johna
    - mariab
    - carlosc

- name: test
  debug:
    msg: "{{ credentials.results }}"
```

The debug message `"{{ credentials.results }}"` gives me the Access Key, but not the Secret Access Key:

```
{
            "ansible_loop_var": "item",
            "changed": true,
            "created_keys": [],
            "failed": false,
            "groups": null,
            "invocation": {
                "module_args": {
                    "access_key_ids": null,
                    "access_key_state": "create",
                    "aws_access_key": null,
                    "aws_secret_key": null,
                    "debug_botocore_endpoint_logs": false,
                    "ec2_url": null,
                    "groups": null,
                    "iam_type": "user",
                    "key_count": 1,
                    "name": "carol.v",
                    "new_name": null,
                    "new_path": null,
                    "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "path": "/",
                    "profile": null,
                    "region": null,
                    "security_token": null,
                    "state": "present",
                    "trust_policy": null,
                    "trust_policy_filepath": null,
                    "update_password": "always",
                    "validate_certs": true
                }
            },
            "item": "carlosc",
            "keys": {
                "AK_________FV": "Active"
            },
            "user_meta": {
                "access_keys": [
                    {
                        "access_key_id": "AK_________FV",
                        "status": "Active"
                    }
                ]
            },
            "user_name": "carlosc"
        }
```

**Comment by tremble** [comment]
`created_keys` has returned [], to me this implies that there was already an access key attached to the user. 

If this is the case then it's *not possible* for Ansible to return the secret key, because, like any 'password', Amazon is storing it in a 'hashed' form which can't be de-crypted (they re-encrypt the key when you pass it to them and compare the two encrypted forms.  This is the same behaviour as the Web UI.

**Comment by lpossamai** [comment]
For further reference. I had to develop a workaround this and would like to share it with you guys. Feel free to visit my repository and [check it out](https://github.com/lpossamai/ansible-iam-cli-keys).

**Comment by goneri** [comment]
Closing per @tremble comment. Thank you all.
