### ISSUE TITLE
Update ec2_vpc_route_table to support Transit Gateway ID

### ISSUE THREAD

**Issue by aedevops** [ansible-collections/amazon.aws#478]
Update the ec2_vpc_route_table "routes" parameter to support transit gateway id. Currently only support gateways, instances, network interfaces, and peering connections. Adding this additional support will make creating routes much easier within a VPC route table.

##### COMPONENT NAME
ec2_vpc_route_table

##### ISSUE TYPE
- Feature Idea

**Comment by mihai-satmarean** [comment]
@tremble for our new shiny automation we really need this, if anything we can test or help please let us know

**Comment by laiminhtrung1997** [comment]
Any news for this feature?
