### ISSUE TITLE
Document use of 'local_action' for AWS modules.

### ISSUE THREAD

**Issue by tremble** [ansible-collections/amazon.aws#54]
##### SUMMARY

With #48 we removed the `local_action` examples and just made sure that the per-module documentation is consistent, we should probably add some kind of foot-note to the docs about being able to use 'local_action' for AWS modules

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

AWS

##### ANSIBLE VERSION

n/a

**Comment by jillr** [comment]
Using `local_action` for (among others) AWS modules is mentioned in the docs for `local_action`, is there anywhere else it makes sense to add a note?  It there a scenario where it would be necessary and non-obvious to specify local_action?

**Comment by jillr** [comment]
@tremble Can we close this issue or is there something we need to do here?

**Comment by goneri** [comment]
waiting_for_contributor

**Comment by goneri** [comment]
Closing per @jillr comment.
