### ISSUE TITLE
Support for Amazon Managed Prometheus

### ISSUE THREAD

**Issue by AnakinPt** [ansible-collections/amazon.aws#554]
### Summary

With the launch of AMP I would like to use Ansible to update my AMP alerts and rules.

### Issue Type

Feature Idea

### Component Name

prometheus

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by gravesm** [comment]
@AnakinPt thank you for submitting this feature request.

**Comment by alinabuzachis** [comment]
Closed because duplicate of https://github.com/ansible-collections/community.aws/issues/855.
