### ISSUE TITLE
ec2_key: support ed25519 key-type

### ISSUE THREAD

**Issue by joejulian** [ansible-collections/amazon.aws#572]
### Summary

Newer distros are beginning to disable rsa sha-1 public keys by default. Supporting the more secure ed25519 key types would allow users to utilize best practices (as long as they're not using them for windows instances). The Windows deficiency should be called out in documentation and the default should remain rsa until this deficiency is fixed by aws.

### Issue Type

Feature Idea

### Component Name

ec2_key

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
This certainly sounds like a good feature.

Would you be interested in trying to add it?

Note for anyone implementing: botocore version 1.21.23 or later will be required for this, and will need to be explicitly used when testing in CI and should only be used when explicitly testing with an ed25519 key.  Compatability with botocore == 1.18.0 must be maintained when using RSA based keys.
