### ISSUE TITLE
ec2_vol tags resources after creating them, instead of at creation time

### ISSUE THREAD

**Issue by imareporter** [ansible-collections/amazon.aws#596]
### Summary

Per an user's request, they would like `ec2_vol` to tag resources at creation time, instead of after.

### Issue Type

Feature Idea

### Component Name

ec2_vol

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by alinabuzachis** [comment]
@imareporter thank you for this idea. This PR https://github.com/ansible-collections/amazon.aws/pull/604 should do it.
