### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by johnpetersjr** [ansible-collections/amazon.aws#64]
##### SUMMARY

On this page: https://github.com/ansible-collections/amazon.aws/contribute 
the link "Read the contributing guidelines" doesn't go anywhere.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Documentation on GitHub

##### ANSIBLE VERSION

```paste below
N/A
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Click the link:
https://github.com/ansible-collections/amazon.aws/contribute and then try to read the contributing guidelines.

```yaml
N/A
```

##### ACTUAL RESULTS

```paste below

```

**Comment by tremble** [comment]
Thanks for taking the time to open the report.

This issue was fixed not long after you opened the issue (I think the PR was in flight at the time) by: #62
