### ISSUE TITLE
amazon.aws.elb_classic_lb purge_listeners is destructive in nature 

### ISSUE THREAD

**Issue by adamkamali** [ansible-collections/amazon.aws#668]
### Summary

Hi Everyone,

I used amazon.aws.elb_classic_lb to add tags to my production env, and all I know is it went and deleted all active listeners, and that took down my production environment. 

Checking the docs and I see` purge unlisted listeners` is set to **yes** by default!. 

This module behaviour should not be **destructive** in nature. Unless you specifically specify to remove them, then it shouldn't just go and delete them! 

This was more like a publishment rather than a fix. 

### Issue Type

Bug Report

### Component Name

amazon.aws.elb_classic_lb

### Ansible Version

ansible 2.9.27 

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

- hosts: localhost
  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
        filters:
          vpc-id: "{{vpc_id}}"
      register: ec2_list

    - set_fact:
        ec2_instances: "{{ec2_list | json_query('instances[*].instance_id') }}"
      
    - name: Ensure tags are present on a resource
      amazon.aws.ec2_tag:
        region: "{{region}}"
        resource: "{{ item }}"
        state: present
        tags:
          provisioner: terraform
          env: production
      loop: "{{ ec2_instances }}"

### Expected Results

This should loop over `ec2_instances` and add tags accordingly. 

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jillr** [comment]
Hi @adamkamali  I'm very sorry to hear about the impact this had.  

While we don't disagree that would be a good default to change, we would need to go through a deprecation period to notify users of a planned change in default behaviour.  Given that Classic LBs will be [discontinued](https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/) on Aug 15th of this year, we are unlikely to have time to do that before the service ceases to exist.
