### ISSUE TITLE
compare_aws_tags should ignore tags with the prefix 'aws:'

### ISSUE THREAD

**Issue by tremble** [ansible-collections/amazon.aws#817]
### Summary

See also: https://github.com/ansible-collections/community.aws/issues/1146

According to the [AWS documentation](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html#tag-conventions)

> System created tags that begin with aws: are reserved for AWS use ... You can't edit or delete a tag that begins with the aws: prefix.

The most common use case here is AWS CloudFormation, which adds a "aws:cloudformation:stack-name" tag.  Since we can't manage these tags at all we should probably ignore them for the purposes of 'purging'.  If someone explicitly adds the tag, then I think it's reasonable to let the APIs throw an error at them, but otherwise we should try to do the best we can.  A possible alternative would be throwing a warning, but that gets a little ugly.

### Issue Type

Feature Idea

### Component Name

plugins/module_utils/tagging.py

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
imo this must be priorized
